name: Run Tests

on:
  push:

jobs:
  find-lowest-number:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Test 1
      run: |
        python find_lowest_number.py test_data/test1_input.txt output1.txt
        diff -wB output1.txt test_data/test1_expected.txt

    - name: Test 2
      run: |
        python find_lowest_number.py test_data/test2_input.txt output2.txt
        diff -wB output2.txt test_data/test2_expected.txt

    - name: Test 3
      run: |
        python find_lowest_number.py test_data/test3_input.txt output3.txt
        diff -wB output3.txt test_data/test3_expected.txt
